#!/usr/bin/env python3
import sys
if __name__ == "__main__":
    args = sys.argv[1:]
    if len(args) == 2:
        print(args[0], args[1])
    elif len(args) == 1:
        splat = args[0].split(":")
        repo = splat[0] or "origin"
        branch = None
        if len(splat) == 2:
            repo = "dev" if splat[0].endswith("-dev") else repo
            branch = splat[1]
        elif len(splat) == 1:
            branch = splat[0]
        print(repo, branch)
